### ISSUE TITLE
No recipes available for weston_1.6.0.bbappend

### ISSUE THREAD

**Issue by leon-anavi** [mickey-happygolucky/meta-weston-rpi#1]
Hi,

I am getting the following error when I follow the tutorial from: http://mickey-happygolucky.hatenablog.com/entry/2015/03/01/160138

```
ERROR: No recipes available for:
  /media/storage/poky-rpi2/meta-weston-rpi/recipes-graphics/wayland/weston_1.6.0.bbappend
```

As far as I see the version of Weston in the master on Poky is 1.8.0. Which release of Poky is supposed to be used to build successfully an image with this tutorial?

Thanks,
Leon

**Comment by mickey-happygolucky** [comment]
Hi, Leon

A version of Weston was 1.6.0, when I was create this recipe.
Could you try renaming the recipe from "weston_1.6.0.bbappend" to "weston_%.bbappend" ?

Thanks,
Yusuke MITSUKI

**Comment by leon-anavi** [comment]
Hi Yusuke,

Thank you for the feedback. You have done very good job with meta-weston-rpi.

I submitted a pull request with several fixes for the latest Yocto release: https://github.com/mickey-happygolucky/meta-weston-rpi/pull/2

I hope you will approve and merge it.

Best regards,
Leon

**Comment by mickey-happygolucky** [comment]
Hi Leon

Thanks for your contribution!!
I approved.

Would you close this issue?

Thanks,
Yusuke MITSUKI

**Comment by mickey-happygolucky** [comment]
I close. thanks.
